-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Users table (extends Supabase Auth)
create table public.users (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.users 
ADD COLUMN  status text default 'Active'

-- Create Categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products table
create table public.products (
  id bigint generated by default as identity primary key,
  "productName" text not null,
  sku text,
  category text,
  price numeric not null,
  "discountPrice" numeric,
  rating numeric default 0,
  stock integer default 0,
  status text default 'In Stock',
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Create Orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.users(id),
  product_id bigint references public.products(id),
  total numeric not null,
  quantity numeric not null,
  status text default 'pending', -- pending, processing, shipped, delivered, cancelled
  -- Delivery Details
  delivery_name text not null,
  delivery_address text not null,
  delivery_phone text not null,
  delivery_email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Create Reviews table (Optional based on mock data)
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  user_id uuid references public.users(id),
  comment text,
  rating integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Disable RLS to allow backend access
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;

create table public.suppliers (
  id bigint generated by default as identity primary key,
  company_name text not null,
  email text not null unique,
  phone text,
  address text not null,
  password text not null, -- In production, this should be hashed
  categories text,
  message text,
  profile_image text,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone
);


create table public.promotions (
  id bigint generated by default as identity primary key,
  code text, -- null for general discounts, specific codes for targeted promotions
  description text not null,
  type text not null, -- 'percentage' or 'fixed'
  value numeric not null,
  start_date date not null,
  end_date date not null,
  applies_to text default 'All Products',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(code) -- Ensure codes are unique (null values are not considered duplicates)
);

create table public.users (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  phone text,
  address text,
  profile_picture text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.reviews
ADD COLUMN   images text;

-- Create Supplier Orders table (for supplier orders)
create table public.supplier_orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  quantity integer not null,
  total_price numeric,
  expected_delivery date not null,
  actual_delivery_date date,
  delivery_notes text,
  status text default 'Pending', -- Pending, Accepted, Dispatched, Delivered, Completed, Rejected
  order_date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Invoices table (for supplier invoices)
create table public.invoices (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete cascade,
  supplier_order_id bigint references public.supplier_orders(id) on delete cascade,
  amount numeric not null,
  issue_date date not null,
  due_date date not null,
  payment_date date,
  status text default 'Pending', -- Pending, Paid, Overdue
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Migration to add status column to users table
-- Run this SQL in your Supabase SQL Editor

-- Add the status column with default value 'Active'
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS status text DEFAULT 'Active';

-- Update any existing records that might not have the status set
UPDATE public.users
SET status = 'Active'
WHERE status IS NULL;

-- Add a check constraint to ensure status is either 'Active' or 'Blocked'
ALTER TABLE public.users
ADD CONSTRAINT users_status_check
CHECK (status IN ('Active', 'Blocked'));

-- Optional: Create an index on status for better query performance
CREATE INDEX IF NOT EXISTS idx_users_status ON public.users(status);

-- Create Cart table
create table public.cart (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  quantity integer not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id) -- Prevent duplicate cart items for same user and product
);


create table public.promo_code_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  used_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references public.orders(id) on delete cascade,
  promotion_id bigint references public.promotions(id) on delete cascade,
  unique(user_id, promotion_id) -- Each user can use each promotion only once
);

ALTER TABLE public.promo_code_usage
ADD COLUMN  promotion_id bigint references public.promotions(id) on delete cascade;

-- Drop old unique constraint and add new one
ALTER TABLE public.promo_code_usage
DROP CONSTRAINT IF EXISTS promo_code_usage_user_id_promo_code_key,
ADD CONSTRAINT promo_code_usage_user_id_promotion_id_key UNIQUE (user_id, promotion_id);

ALTER TABLE public.orders
ADD COLUMN promo_code text,
ADD COLUMN discount_amount numeric default 0

SET session_replication_role = 'replica';

TRUNCATE TABLE public.promo_code_usage CASCADE;
TRUNCATE TABLE public.cart CASCADE;
TRUNCATE TABLE public.reviews CASCADE;
TRUNCATE TABLE public.orders CASCADE;
TRUNCATE TABLE public.supplier_orders CASCADE;
TRUNCATE TABLE public.invoices CASCADE;
TRUNCATE TABLE public.products CASCADE;
TRUNCATE TABLE public.suppliers CASCADE;
TRUNCATE TABLE public.promotions CASCADE;
TRUNCATE TABLE public.users CASCADE;

-- Migration: Update promotions table to allow null codes for general discounts
-- Run this SQL in your Supabase SQL Editor
ALTER TABLE public.promotions ALTER COLUMN code DROP NOT NULL;

-- Migration: Update promotions table to use default code for general discounts
-- Run this SQL in your Supabase SQL Editor if you have existing data
-- First, check if GENERAL_DISCOUNT already exists, if not, update null codes
-- UPDATE public.promotions SET code = 'GENERAL_DISCOUNT' WHERE code IS NULL AND NOT EXISTS (SELECT 1 FROM public.promotions WHERE code = 'GENERAL_DISCOUNT');
-- Create Payments table
create table public.payments (
  payment_id bigint generated by default as identity primary key,
  payment_type text not null, -- 'card' or 'cash'
  payment_date timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  customer_id uuid references public.users(id),
  card_holder text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.customer_contact_form (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  first_name text not null,
  last_name text not null,
  mobile_number text,
  email text not null,
  message text not null,
  response text,
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.refund_requests (
  refund_request_id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  user_id uuid references public.users(id) not null,
  message text not null,
  response text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.supplier_contact_form (
  supplier_contact_form_id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

A L T E R   T A B L E   p u b l i c . s u p p l i e r _ c o n t a c t _ f o r m   A D D   C O L U M N   I F   N O T   E X I S T S   r e s p o n s e   t e x t ;   A L T E R   T A B L E   p u b l i c . s u p p l i e r _ c o n t a c t _ f o r m   A D D   C O L U M N   I F   N O T   E X I S T S   s t a t u s   t e x t   D E F A U L T   ' P e n d i n g ' ;  
 