-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Users table (extends Supabase Auth)
create table public.users (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  phone text,
  address text,
  profile_picture text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products table
create table public.products (
  id bigint generated by default as identity primary key,
  "productName" text not null,
  sku text,
  category text,
  price numeric not null,
  "discountPrice" numeric,
  images text[],
  rating numeric default 0,
  stock integer default 0,
  status text default 'In Stock',
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.users(id),
  total numeric not null,
  status text default 'pending', -- pending, processing, shipped, delivered, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null,
  price numeric not null, -- Price at the time of purchase
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Reviews table (Optional based on mock data)
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  user_id uuid references public.users(id),
  comment text,
  rating integer,
  images text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Suppliers table
create table public.suppliers (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_person text not null,
  email text not null unique,
  phone text,
  password text not null, -- In production, this should be hashed
  categories text not null,
  message text,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone
);

-- Create Promotions table
create table public.promotions (
  id bigint generated by default as identity primary key,
  code text unique, -- Made optional and unique (can be null for general discounts)
  description text not null,
  type text not null, -- 'percentage' or 'fixed'
  value numeric not null,
  start_date date not null,
  end_date date not null,
  applies_to text default 'All Products',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Purchase Orders table (for admin to supplier orders)
create table public.purchase_orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  quantity integer not null,
  price_per_unit numeric not null,
  expected_delivery date not null,
  actual_delivery_date date,
  delivery_notes text,
  status text default 'Pending', -- Pending, Accepted, Rejected, Dispatched, Delivered, Completed
  order_date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert sample data
-- Note: These inserts assume specific user IDs from Supabase Auth. In a real setup, you'd use actual UUIDs.

-- Sample Reviews
INSERT INTO public.reviews (product_id, user_id, comment, rating) VALUES
(1, '00000000-0000-0000-0000-000000000001', 'Great quality furniture! Very comfortable and stylish.', 5),
(1, '00000000-0000-0000-0000-000000000002', 'Excellent craftsmanship. Worth every penny.', 4),
(2, '00000000-0000-0000-0000-000000000001', 'Beautiful design, but a bit pricey.', 4),
(2, '00000000-0000-0000-0000-000000000003', 'Love the color and finish. Highly recommend!', 5),
(3, '00000000-0000-0000-0000-000000000002', 'Good value for money. Sturdy build.', 4),
(3, '00000000-0000-0000-0000-000000000003', 'Perfect for my living room. Very satisfied.', 5);
