-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Users table (extends Supabase Auth)
create table public.users (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  role text default 'customer',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Categories table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products table
create table public.products (
  id bigint generated by default as identity primary key,
  "productName" text not null,
  sku text,
  category text,
  price numeric not null,
  "discountPrice" numeric,
  images text[],
  rating numeric default 0,
  stock integer default 0,
  status text default 'In Stock',
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.users(id),
  total numeric not null,
  status text default 'pending', -- pending, processing, shipped, delivered, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items table
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null,
  price numeric not null, -- Price at the time of purchase
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Reviews table (Optional based on mock data)
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  user_id uuid references public.users(id),
  comment text,
  rating integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Suppliers table
create table public.suppliers (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_person text not null,
  email text not null unique,
  phone text,
  password text not null, -- In production, this should be hashed
  categories text not null,
  message text,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone
);
