const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase configuration in .env file');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function setupDatabase() {
  try {
    console.log('Setting up database tables...');

    // Check if suppliers table exists
    const { data: tables } = await supabase
      .from('information_schema.tables')
      .select('table_name')
      .eq('table_schema', 'public')
      .eq('table_name', 'suppliers');

    if (tables && tables.length > 0) {
      console.log('Suppliers table already exists');
      return;
    }

    // Create suppliers table using SQL
    const { error } = await supabase.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS public.suppliers (
          id bigint generated by default as identity primary key,
          company_name text not null,
          contact_person text not null,
          email text not null unique,
          phone text,
          password text not null,
          categories text not null,
          message text,
          status text default 'pending',
          created_at timestamp with time zone default timezone('utc'::text, now()) not null,
          approved_at timestamp with time zone,
          rejected_at timestamp with time zone
        );
      `
    });

    if (error) {
      console.error('Error creating suppliers table:', error);
      // Try direct SQL execution
      console.log('Attempting direct SQL execution...');
      const { error: sqlError } = await supabase
        .from('suppliers')
        .select('*')
        .limit(1);

      if (sqlError && sqlError.message.includes('relation "public.suppliers" does not exist')) {
        console.log('Suppliers table does not exist. Please run the SQL from schema.sql in your Supabase dashboard.');
        console.log('SQL to run:');
        console.log(`
CREATE TABLE public.suppliers (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_person text not null,
  email text not null unique,
  phone text,
  password text not null,
  categories text not null,
  message text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone
);
        `);
      }
    } else {
      console.log('Suppliers table created successfully');
    }

  } catch (error) {
    console.error('Setup error:', error);
  }
}

setupDatabase();