const supabase = require('./config/supabaseClient');

async function createPromotionsTable() {
  try {
    console.log('Creating promotions table...');

    const { error } = await supabase.rpc('exec_sql', {
      sql: `
        -- Create Promotions table
        create table if not exists public.promotions (
          id bigint generated by default as identity primary key,
          code text not null unique,
          description text not null,
          type text not null, -- 'percentage' or 'fixed'
          value numeric not null,
          start_date date not null,
          end_date date not null,
          applies_to text default 'All Products',
          is_active boolean default true,
          created_at timestamp with time zone default timezone('utc'::text, now()) not null,
          updated_at timestamp with time zone default timezone('utc'::text, now()) not null
        );
      `
    });

    if (error) {
      console.error('Error creating table:', error);
      throw error;
    }

    console.log('Promotions table created successfully!');
  } catch (error) {
    console.error('Failed to create promotions table:', error);
  }
}

createPromotionsTable();